"""add course_hw_no to homework

Revision ID: 135d77acf2e3
Revises: 81b368a4fe7f
Create Date: 2025-10-11 19:10:37.246389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '135d77acf2e3'
down_revision = '81b368a4fe7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('homework', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course_hw_no', sa.Integer(), nullable=False, comment='同一课程内的作业序号'))
        batch_op.create_index(batch_op.f('ix_homework_course_id'), ['course_id'], unique=False)
        batch_op.create_unique_constraint('unique_course_hw_no', ['course_id', 'course_hw_no'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('homework', schema=None) as batch_op:
        batch_op.drop_constraint('unique_course_hw_no', type_='unique')
        batch_op.drop_index(batch_op.f('ix_homework_course_id'))
        batch_op.drop_column('course_hw_no')

    # ### end Alembic commands ###
