"""Add max_score field to Homework

Revision ID: b80bbc9c820b
Revises: 2324c023df8e
Create Date: 2025-12-18 05:19:06.732046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b80bbc9c820b'
down_revision = '2324c023df8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('homework', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_score', sa.Integer(), nullable=False, server_default='100', comment='本次作业分数上限'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('homework', schema=None) as batch_op:
        batch_op.drop_column('max_score')

    # ### end Alembic commands ###
